<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <joint name="face_joint" type="fixed">
        <parent link="chassis"/>
        <child link="face_link"/>
        <origin xyz="${chassis_length} 0 ${chassis_height/2}" rpy="0 0 0"/>
    </joint>

    <link name="face_link">
        <visual>
            <origin xyz="0 0.08 0.02" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder radius="0.025" length="0.003"/>
            </geometry>
            <material name="black"/>
        </visual>

        <visual>
            <origin xyz="0 -0.08 0.02" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder radius="0.025" length="0.003"/>
            </geometry>
            <material name="black"/>
        </visual>


        <visual>
            <origin xyz="-0.011 0 -0.05" rpy="0 ${1.5} 0"/>
            <geometry>
                <cylinder radius="0.045" length="0.0225"/>
            </geometry>
            <material name="red"/>
        </visual>
    </link>

    <gazebo reference="face_link">
        <material>Gazebo/Black</material>
    </gazebo>


</robot>